# Ustawienia JVM dla Gradle
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
# AndroidX wymagane dla nowoczesnych bibliotek
android.useAndroidX=true
# Kotlin code style
kotlin.code.style=official
# Nie generuj zbędnych BuildConfig itd. per moduł (defaulty AGP 8 są OK)
org.gradle.configuration-cache=true
